import { useEffect, useState } from "react";
import axios from "axios";

import Head from "next/head";

import Componente from "@/components/Componente"
import data from "@/data/data";

export default function Home() {

  const apiUrl = "https://lanciweb.github.io/demo/api";
  const actorsEndpoint = "actors"
  const actressesEndpoint = "actresses"

  function getActors() {
    axios.get(`${apiUrl}/${actorsEndpoint}`).then((r) => {
      console.log("Attori", r.data);
      axios.get(`${apiUrl}/${actressesEndpoint}`).then((r) => {
        console.log("Attrici", r.data);
      }).catch((e) => {
        console.log("Errore", e.message);
      })
    }).catch((e) => {
      console.log("Errore", e.message);
    })
  }

  
  useEffect(getActors, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Componente proprieta={x} /> */}

      <button onClick={getActors}>Carica</button>
    </>
  );
}
