import { useEffect, useState } from "react";
import axios from "axios";

import Head from "next/head";

import Componente from "@/components/Componente"
import ActorsList from "@/components/ActrorsList"
import data from "@/data/data";

export default function Home() {
  const apiUrl = "https://lanciweb.github.io/demo/api";
  const actorsEndpoint = "actors"
  const actressesEndpoint = "actresses"

  const [actors, setActors] = useState([])
  const [actresses, setActresses] = useState([])

  const [yearOfBirth, setYearOfBirth] = useState("")

  function getActors() {
    axios.get(`${apiUrl}/${actorsEndpoint}`).then((r) => {
      console.log("Attori", r.data);

      setActors(r.data)
    }).catch((e) => {
      console.log("Errore", e.message);
    })
  }

  function getActresses() {
    axios.get(`${apiUrl}/${actressesEndpoint}`).then((r) => {
      console.log("Attrici", r.data);
      setActresses(r.data)
    }).catch((e) => {
      console.log("Errore", e.message);
    })
  }

  useEffect(() => {
    getActors()
    getActresses()
  }, [])

  function handleYearOfBirthChange(e) {
    setYearOfBirth(e.target.value)
  }

  console.log(yearOfBirth)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Componente proprieta={x} /> */}

      {/* <button onClick={getActors}>Carica</button> */}

      <div>
        Filtra per anno di nascita
        <input value={yearOfBirth} onChange={handleYearOfBirthChange} />
      </div>

      <ActorsList actors={actors.filter(actor => actor.birth_year == yearOfBirth)} actresses={actresses.filter(actress => actress.birth_year == yearOfBirth)} />
    </>
  );
}
