import { useEffect, useState } from "react";
import axios from "axios";

import Head from "next/head";

import Componente from "@/components/Componente"
import ActorsList from "@/components/ActrorsList"
import data from "@/data/data";

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Componente proprieta={x} /> */}

      {/* <button onClick={getActors}>Carica</button> */}

      <ActorsList />
    </>
  );
}
